default: &default
  super_subdomain: 'super'
  default_subdomain: 'www'
  app_name: 'Spike76'
  redis:
    host: redis
    sidekiq_db: 1
  elasticsearch:
    host: elasticsearch

development:
  <<: *default

production:
  <<: *default